<div class="practice--panel--ejs8J"><div data-purpose="practice-component-text" class="rt-scaffolding"><h4>Lab Objective: Load &amp; process <strong>JSON</strong> data</h4><p>This lab guides you through loading JSON data into a Snowflake table using an external stage. The external stage in this example will point to data in an S3 bucket.</p><p><br></p><ol><li><p>Create a new database in your Snowflake instance by the name of dev_lnd. We have used the <em>dev_lnd</em> naming convention to represent the landing database in the development environment. We will use this database for loading data.</p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">CREATE DATABASE dev_lnd</span><span class="pun">;</span></li></ol></pre></div></div><p><br></p></li><li><p>In the dev_lnd database, create a new table temporarily holding the JSON data so we can process it further into a tabular format. The table has a single column of data type VARIANT. VARIANT is a special data type in Snowflake that can hold any data.</p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">USE DATABASE dev_lnd</span><span class="pun">;</span></li><li class="L1"><span class="pln">USE SCHEMA </span><span class="kwd">public</span><span class="pun">;</span></li><li class="L2"><span class="pln">&nbsp;</span></li><li class="L3"><span class="pln">CREATE TABLE flight_data_json</span></li><li class="L4"><span class="pun">(</span></li><li class="L5"><span class="pln">json_data VARIANT</span></li><li class="L6"><span class="pun">);</span></li></ol></pre></div></div><p><br></p></li><li><p>Download &amp; familiarize yourself with the structure of the JSON data that we will load in this lab. You can access the JSON file for this lab at <a target="_blank" rel="noopener noreferrer" href="https://ca-flight-json-data-daily.s3.amazonaws.com/2020/07/01/flights_data_20200701.json">https://ca-flight-json-data-daily.s3.amazonaws.com/2020/07/01/flights_data_20200701.json</a></p><p><br></p><p>Note that the file contains data for 1st July 2020 only.</p><p><br></p></li><li><p>The structure of the file is shown below. The file contains a <em>flights</em> array, where each record in the array contains information related to a single flight.</p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pun">{</span></li><li class="L1"><span class="pun">“</span><span class="pln">flights</span><span class="pun">”:[</span></li><li class="L2"><span class="pun">--</span><span class="lit">1st</span><span class="pln"> flight record</span></li><li class="L3"><span class="pun">{</span></li><li class="L4"><span class="str">"FL_DATE"</span><span class="pun">:</span><span class="str">"2020-06-02"</span></li><li class="L5"><span class="pun">,</span><span class="str">"OP_UNIQUE_CARRIER"</span><span class="pun">:</span><span class="str">"AA"</span></li><li class="L6"><span class="pun">,</span><span class="str">"OP_CARRIER_AIRLINE_ID"</span><span class="pun">:</span><span class="str">"19805"</span></li><li class="L7"><span class="pun">,</span><span class="str">"OP_CARRIER"</span><span class="pun">:</span><span class="str">"AA"</span></li><li class="L8"><span class="pun">,</span><span class="str">"TAIL_NUM"</span><span class="pun">:</span><span class="str">"N994AN"</span></li><li class="L9"><span class="pun">,</span><span class="str">"OP_CARRIER_FL_NUM"</span><span class="pun">:</span><span class="str">"496"</span></li><li class="L0"><span class="pun">,</span><span class="str">"ORIGIN"</span><span class="pun">:{</span></li><li class="L1"><span class="str">"ORIGIN_AIRPORT_ID"</span><span class="pun">:</span><span class="str">"11298"</span></li><li class="L2"><span class="pun">,</span><span class="str">"ORIGIN_AIRPORT_SEQ_ID"</span><span class="pun">:</span><span class="str">"1129806"</span></li><li class="L3"><span class="pun">,</span><span class="str">"ORIGIN_CITY_MARKET_ID"</span><span class="pun">:</span><span class="str">"30194"</span></li><li class="L4"><span class="pun">,</span><span class="str">"ORIGIN"</span><span class="pun">:</span><span class="str">"DFW"</span></li><li class="L5"><span class="pun">,</span><span class="str">"ORIGIN_STATE_ABR"</span><span class="pun">:</span><span class="str">"TX"</span></li><li class="L6"><span class="pun">,</span><span class="str">"ORIGIN_STATE_FIPS"</span><span class="pun">:</span><span class="str">"48"</span></li><li class="L7"><span class="pun">,</span><span class="str">"ORIGIN_WAC"</span><span class="pun">:</span><span class="str">"74"</span></li><li class="L8"><span class="pun">,</span><span class="str">"DEP_TIME"</span><span class="pun">:</span><span class="str">"1447"</span></li><li class="L9"><span class="pun">,</span><span class="str">"DEP_DELAY"</span><span class="pun">:</span><span class="str">"-3.00"</span></li><li class="L0"><span class="pun">,</span><span class="str">"TAXI_OUT"</span><span class="pun">:</span><span class="str">"26.00"</span></li><li class="L1"><span class="pun">,</span><span class="str">"WHEELS_OFF"</span><span class="pun">:</span><span class="str">"1513"</span></li><li class="L2"><span class="pun">}</span></li><li class="L3"><span class="pun">,</span><span class="str">"DESTINATION"</span><span class="pun">:{</span></li><li class="L4"><span class="str">"DEST_AIRPORT_ID"</span><span class="pun">:</span><span class="str">"13303"</span></li><li class="L5"><span class="pun">,</span><span class="str">"DEST_AIRPORT_SEQ_ID"</span><span class="pun">:</span><span class="str">"1330303"</span></li><li class="L6"><span class="pun">,</span><span class="str">"DEST_CITY_MARKET_ID"</span><span class="pun">:</span><span class="str">"32467"</span></li><li class="L7"><span class="pun">,</span><span class="str">"DEST"</span><span class="pun">:</span><span class="str">"MIA"</span></li><li class="L8"><span class="pun">,</span><span class="str">"DEST_STATE_ABR"</span><span class="pun">:</span><span class="str">"FL"</span></li><li class="L9"><span class="pun">,</span><span class="str">"DEST_STATE_FIPS"</span><span class="pun">:</span><span class="str">"12"</span></li><li class="L0"><span class="pun">,</span><span class="str">"DEST_WAC"</span><span class="pun">:</span><span class="str">"33"</span></li><li class="L1"><span class="pun">,</span><span class="str">"WHEELS_ON"</span><span class="pun">:</span><span class="str">"1832"</span></li><li class="L2"><span class="pun">,</span><span class="str">"TAXI_IN"</span><span class="pun">:</span><span class="str">"5.00"</span></li><li class="L3"><span class="pun">,</span><span class="str">"ARR_TIME"</span><span class="pun">:</span><span class="str">"1837"</span></li><li class="L4"><span class="pun">,</span><span class="str">"ARR_DELAY"</span><span class="pun">:</span><span class="str">"-10.00"</span></li><li class="L5"><span class="pun">}</span></li><li class="L6"><span class="pln">&nbsp;</span></li><li class="L7"><span class="pun">,</span><span class="str">"CANCELLED"</span><span class="pun">:</span><span class="str">"0.00"</span></li><li class="L8"><span class="pun">,</span><span class="str">"CANCELLATION_CODE"</span><span class="pun">:</span><span class="str">""</span></li><li class="L9"><span class="pun">,</span><span class="str">"DIVERTED"</span><span class="pun">:</span><span class="str">"0.00"</span></li><li class="L0"><span class="pun">,</span><span class="str">"ACTUAL_ELAPSED_TIME"</span><span class="pun">:</span><span class="str">"170.00"</span></li><li class="L1"><span class="pun">,</span><span class="str">"AIR_TIME"</span><span class="pun">:</span><span class="str">"139.00"</span></li><li class="L2"><span class="pun">,</span><span class="str">"FLIGHTS"</span><span class="pun">:</span><span class="str">"1.00"</span></li><li class="L3"><span class="pun">,</span><span class="str">"DISTANCE"</span><span class="pun">:</span><span class="str">"1121.00"</span></li><li class="L4"><span class="pun">,</span><span class="str">"CARRIER_DELAY"</span><span class="pun">:</span><span class="str">""</span></li><li class="L5"><span class="pun">,</span><span class="str">"WEATHER_DELAY"</span><span class="pun">:</span><span class="str">""</span></li><li class="L6"><span class="pun">,</span><span class="str">"NAS_DELAY"</span><span class="pun">:</span><span class="str">""</span></li><li class="L7"><span class="pun">,</span><span class="str">"SECURITY_DELAY"</span><span class="pun">:</span><span class="str">""</span></li><li class="L8"><span class="pun">,</span><span class="str">"LATE_AIRCRAFT_DELAY"</span><span class="pun">:</span><span class="str">""</span></li><li class="L9"><span class="pun">},</span></li><li class="L0"><span class="pun">--</span><span class="lit">2nd</span><span class="pln"> flight record</span></li><li class="L1"><span class="pun">{</span></li><li class="L2"><span class="str">"FL_DATE"</span><span class="pun">:</span><span class="str">"2020-06-02"</span></li><li class="L3"><span class="pun">,</span><span class="str">"OP_UNIQUE_CARRIER"</span><span class="pun">:</span><span class="str">"AA"</span></li><li class="L4"><span class="pun">,</span><span class="str">"OP_CARRIER_AIRLINE_ID"</span><span class="pun">:</span><span class="str">"19805"</span></li><li class="L5"><span class="pun">....</span></li><li class="L6"><span class="pun">....</span></li><li class="L7"><span class="pun">....</span></li><li class="L8"><span class="pun">}</span></li><li class="L9"><span class="pun">]</span></li><li class="L0"><span class="pun">}</span></li></ol></pre></div></div><p><br></p><p><br></p></li><li><p>Let us create the external stage pointing to the above location. When creating an external stage, you will use the S3 URI rather than the HTTP version shown in the previous step. The S3 URI for the folder containing the above file is <strong><em>s3://ca-flight-json-data-daily/2020/07/01/.</em></strong> We have specified JSON as the file format so that Snowflake processes the ingested data as JSON.</p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">CREATE OR REPLACE STAGE flights_json_stage</span></li><li class="L1"><span class="pln">url</span><span class="pun">=</span><span class="str">'s3://ca-flight-json-data-daily/2020/07/01/'</span></li><li class="L2"><span class="pln">file_format </span><span class="pun">=</span><span class="pln"> </span><span class="pun">(</span><span class="pln">type </span><span class="pun">=</span><span class="pln"> </span><span class="str">'JSON'</span><span class="pun">);</span></li></ol></pre></div></div><p>Note that the above S3 bucket has been made public to simplify the process of loading data. If you are loading data from a secured bucket, we cover additional security access configuration steps in a separate exercise.</p><p><br></p></li><li><p>Next, we list the content of the external stage and validate that we can see the files in the external stage. To do so, run the LIST command.</p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">LIST </span><span class="lit">@flights_json_stage</span><span class="pun">;</span></li></ol></pre></div></div><p>You should see the following file listed</p><p>s3://ca-flight-json-data-daily/2020/07/01/flights_data_20200701.json</p><p><br></p></li><li><p>Before we load this data into the table, let us parse the data and validate that the data is a valid JSON file. This is just a step for debugging and is not necessarily required for production data loads.</p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">SELECT PARSE_JSON</span><span class="pun">(</span><span class="pln">$1</span><span class="pun">)</span></li><li class="L1"><span class="pln">FROM </span><span class="lit">@flights_json_stage</span><span class="pun">;</span></li></ol></pre></div></div><p>The parse command should be complete without errors, and you should see one row containing JSON data. Note that $1 used in the syntax above is another way of accessing columns in a table or a stage. So $1 refers to the first column.</p><p><br></p></li><li><p>Let us load the data into the FLIGHT_DATA_JSON table from the external stage. We will use the standard COPY command to load the data from the external stage.</p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">USE DATABASE dev_lnd</span><span class="pun">;</span></li><li class="L1"><span class="pln">COPY INTO flight_data_json</span></li><li class="L2"><span class="pln">FROM </span><span class="lit">@flights_json_stage</span><span class="pun">;</span></li></ol></pre></div></div><p><br></p></li><li><p>The previous command loads 1 row, which is the complete JSON file. You can validate the load again by selecting data from the table.</p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">SELECT </span><span class="pun">*</span><span class="pln"> FROM flight_data_json</span><span class="pun">;</span></li></ol></pre></div></div><p>This will return a single row, which is the complete JSON file. The result will look like the following.</p><p><br></p><p><code>{ "flights": [ { "ACTUAL_ELAPSED_TIME": "52.00", "AIR_TIME": "38.00", "CANCELLATION_CODE": "", "CANCELLED": "0.00", "CARRIER_DELAY": "", "DESTINATION………….</code></p><p><br></p></li><li><p>You would have noted from the structure shown in step 4 that all data is contained in the <em>flights</em> array. Through the next few steps, we will extract data out of this array in an incremental manner. Start by selecting the <em>flights</em> array object and reviewing the output.</p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">SELECT json_data</span><span class="pun">:</span><span class="pln">flights FROM flight_data_json</span><span class="pun">;</span></li></ol></pre></div></div><p><br></p></li><li><p>Since <em>flights</em> is a JSON array, we can access elements of this array using a numerical value. For example, to access the first value, run the following SQL.</p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">SELECT json_data</span><span class="pun">:</span><span class="pln">flights</span><span class="pun">[</span><span class="lit">0</span><span class="pun">]</span><span class="pln"> FROM flight_data_json</span><span class="pun">;</span></li></ol></pre></div></div><p><br></p><p>The result of this SQL is the first element of the JSON array. Each element of the JSON array contains data for a single flight. The result would look similar to the following.</p><p><br></p><p><code>{ "ACTUAL_ELAPSED_TIME": "52.00", "AIR_TIME": "38.00", "CANCELLATION_CODE": "", "CANCELLED": "0.00", "CARRIER_DELAY": "", "DESTINATION": { "ARR_D…………………..</code></p><p><br></p></li><li><p>Now we can try and access an individual element from this array, for example, the FL_DATE element.</p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">SELECT json_data</span><span class="pun">:</span><span class="pln">flights</span><span class="pun">[</span><span class="lit">0</span><span class="pun">].</span><span class="pln">FL_DATE</span></li><li class="L1"><span class="pln">FROM flight_data_json</span><span class="pun">;</span></li></ol></pre></div></div><p><br></p></li><li><p>Similarly, we can access other elements in the JSON array per our requirements, as shown in the example SQL below. </p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">SELECT json_data</span><span class="pun">:</span><span class="pln">flights</span><span class="pun">[</span><span class="lit">0</span><span class="pun">].</span><span class="pln">FL_DATE</span><span class="pun">,</span></li><li class="L1"><span class="pln">json_data</span><span class="pun">:</span><span class="pln">flights</span><span class="pun">[</span><span class="lit">0</span><span class="pun">].</span><span class="pln">OP_CARRIER_FL_NUM</span><span class="pun">,</span></li><li class="L2"><span class="pln">json_data</span><span class="pun">:</span><span class="pln">flights</span><span class="pun">[</span><span class="lit">0</span><span class="pun">].</span><span class="pln">ORIGIN</span><span class="pun">,</span></li><li class="L3"><span class="pln">json_data</span><span class="pun">:</span><span class="pln">flights</span><span class="pun">[</span><span class="lit">0</span><span class="pun">].</span><span class="pln">DESTINATION</span></li><li class="L4"><span class="pln">FROM flight_data_json</span><span class="pun">;</span></li></ol></pre></div></div><p><br></p></li><li><p>Note that the ORIGIN &amp; the DESTINATION elements are nested JSON elements with further sub-elements. If you need sub-elements, you access them through the . syntax as shown below.</p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">SELECT json_data</span><span class="pun">:</span><span class="pln">flights</span><span class="pun">[</span><span class="lit">0</span><span class="pun">].</span><span class="pln">FL_DATE</span><span class="pun">,</span></li><li class="L1"><span class="pln">json_data</span><span class="pun">:</span><span class="pln">flights</span><span class="pun">[</span><span class="lit">0</span><span class="pun">].</span><span class="pln">OP_CARRIER_FL_NUM</span><span class="pun">,</span></li><li class="L2"><span class="pln">json_data</span><span class="pun">:</span><span class="pln">flights</span><span class="pun">[</span><span class="lit">0</span><span class="pun">].</span><span class="pln">ORIGIN</span><span class="pun">.</span><span class="pln">ORIGIN_STATE_ABR</span><span class="pun">,</span></li><li class="L3"><span class="pln">json_data</span><span class="pun">:</span><span class="pln">flights</span><span class="pun">[</span><span class="lit">0</span><span class="pun">].</span><span class="pln">ORIGIN</span><span class="pun">.</span><span class="pln">DEP_TIME</span><span class="pun">,</span></li><li class="L4"><span class="pln">json_data</span><span class="pun">:</span><span class="pln">flights</span><span class="pun">[</span><span class="lit">0</span><span class="pun">].</span><span class="pln">DESTINATION</span><span class="pun">.</span><span class="pln">DEST_STATE_ABR</span><span class="pun">,</span></li><li class="L5"><span class="pln">json_data</span><span class="pun">:</span><span class="pln">flights</span><span class="pun">[</span><span class="lit">0</span><span class="pun">].</span><span class="pln">DESTINATION</span><span class="pun">.</span><span class="pln">ARR_TIME</span></li><li class="L6"><span class="pln">&nbsp;</span></li><li class="L7"><span class="pln">FROM flight_data_json</span><span class="pun">;</span></li></ol></pre></div></div><p><br></p></li><li><p>So far, we have seen that we can parse and extract elements out of the loaded JSON. However, the data is not in a tabular format that we can use in queries like other tables. For example, we can access individual elements of the <em>flights</em> array by specifying the element position, but it is not feasible to access each element by its position. We need to pivot the JSON data so that each element in the array becomes a row and the final data is tabular. We will use the FLATTEN function to convert the JSON array into rows. FLATTEN is a built-in Snowflake function that can convert compound values into multiple rows. It is often used to convert semi-structured data into a relational or tabular view. To do so, run the following SQL.</p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">SELECT</span></li><li class="L1"><span class="pun">*</span></li><li class="L2"><span class="pln">FROM</span></li><li class="L3"><span class="pln">flight_data_json</span></li><li class="L4"><span class="pun">,</span><span class="pln"> LATERAL FLATTEN</span><span class="pun">(</span><span class="pln"> input </span><span class="pun">=&gt;</span><span class="pln"> flight_data_json</span><span class="pun">.</span><span class="pln">json_data</span><span class="pun">:</span><span class="pln">flights </span><span class="pun">);</span></li></ol></pre></div></div><p>The SQL will produce 48 rows, which is the number of array elements in the JSON. The lateral function takes as input an object of type VARIANT, OBJECT, or ARRAY and explodes that into rows. In this case, we provided the flight array as input to the function. The following screenshot shows the result (only the first two rows are shown).</p><p><br></p><figure><img src="https://github.com/melwinmpk/Snowflake/assets/25386607/4a04f343-c999-4c27-b296-4967fe1898ec"></figure><p><br></p></li><li><p>The VALUE column here contains the JSON for each row after the FLATTEN function has converted the array into multiple rows. We will use the VALUE column to extract the individual value for each row.</p><p><br></p></li><li><p>We can extract individual columns using the value column, as shown below.</p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">SELECT</span></li><li class="L1"><span class="pln">value</span><span class="pun">:</span><span class="pln">FL_DATE</span><span class="pun">,</span></li><li class="L2"><span class="pln">value</span><span class="pun">:</span><span class="pln">OP_CARRIER_FL_NUM</span><span class="pun">,</span></li><li class="L3"><span class="pln">value</span><span class="pun">:</span><span class="pln">ORIGIN</span><span class="pun">.</span><span class="pln">ORIGIN_STATE_ABR</span><span class="pun">,</span></li><li class="L4"><span class="pln">value</span><span class="pun">:</span><span class="pln">ORIGIN</span><span class="pun">.</span><span class="pln">DEP_TIME</span><span class="pun">,</span></li><li class="L5"><span class="pln">value</span><span class="pun">:</span><span class="pln">DESTINATION</span><span class="pun">.</span><span class="pln">DEST_STATE_ABR</span><span class="pun">,</span></li><li class="L6"><span class="pln">value</span><span class="pun">:</span><span class="pln">DESTINATION</span><span class="pun">.</span><span class="pln">ARR_TIME</span></li><li class="L7"><span class="pln">FROM</span></li><li class="L8"><span class="pln">flight_data_json</span></li><li class="L9"><span class="pun">,</span><span class="pln"> LATERAL FLATTEN</span><span class="pun">(</span><span class="pln"> input </span><span class="pun">=&gt;</span><span class="pln"> flight_data_json</span><span class="pun">.</span><span class="pln">json_data</span><span class="pun">:</span><span class="pln">flights </span><span class="pun">);</span></li></ol></pre></div></div><p><br></p></li><li><p>And if you want, you can set the data type of each column and name each column as shown in the following SQL. You can also add additional columns as needed.</p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">SELECT</span></li><li class="L1"><span class="pln">value</span><span class="pun">:</span><span class="pln">FL_DATE</span><span class="pun">::</span><span class="typ">Date</span><span class="pln"> AS </span><span class="typ">Flight_Date</span><span class="pun">,</span></li><li class="L2"><span class="pln">value</span><span class="pun">:</span><span class="pln">OP_CARRIER_FL_NUM</span><span class="pun">::</span><span class="typ">String</span><span class="pln"> AS </span><span class="typ">Airline_Flight_Number</span><span class="pun">,</span></li><li class="L3"><span class="pln">value</span><span class="pun">:</span><span class="pln">ORIGIN</span><span class="pun">.</span><span class="pln">ORIGIN_STATE_ABR</span><span class="pun">::</span><span class="typ">String</span><span class="pln"> AS </span><span class="typ">Origin_State_Code</span><span class="pun">,</span></li><li class="L4"><span class="pln">value</span><span class="pun">:</span><span class="pln">ORIGIN</span><span class="pun">.</span><span class="pln">DEP_TIME</span><span class="pun">::</span><span class="typ">Number</span><span class="pln"> AS </span><span class="typ">Departure_Time</span><span class="pun">,</span></li><li class="L5"><span class="pln">value</span><span class="pun">:</span><span class="pln">DESTINATION</span><span class="pun">.</span><span class="pln">DEST_STATE_ABR</span><span class="pun">::</span><span class="typ">String</span><span class="pln"> AS </span><span class="typ">Dest_State_Code</span><span class="pun">,</span></li><li class="L6"><span class="pln">value</span><span class="pun">:</span><span class="pln">DESTINATION</span><span class="pun">.</span><span class="pln">ARR_TIME</span><span class="pun">::</span><span class="typ">Number</span><span class="pln"> AS </span><span class="typ">Arrival_Time</span></li><li class="L7"><span class="pln">FROM</span></li><li class="L8"><span class="pln">flight_data_json</span></li><li class="L9"><span class="pun">,</span><span class="pln"> LATERAL FLATTEN</span><span class="pun">(</span><span class="pln"> input </span><span class="pun">=&gt;</span><span class="pln"> flight_data_json</span><span class="pun">.</span><span class="pln">json_data</span><span class="pun">:</span><span class="pln">flights </span><span class="pun">);</span></li></ol></pre></div></div></li></ol><p><br></p><p><br></p><p><br></p></div><div class="practice--question-list--1HR9g practice--mt-md--3j-aS" data-purpose="question-list"><h4 class="ud-heading-md practice--mb-xs--Lpg-b">Questions for this assignment</h4><div><div class="question--question--152Yi"><div class="ud-text-bold question--title--2FD-U"><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="question--title-text--2kBEO rt-scaffolding"><p>How many rows are produced after you have executed the FLATTEN function on the JSON to convert the data to tabular format?</p></div></div><div class="question--answer--2ASXa"></div></div></div></div></div>

<div class="question--question--152Yi"><div class="ud-text-bold question--title--2FD-U"><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="question--title-text--2kBEO rt-scaffolding"><p>How many rows are produced after you have executed the FLATTEN function on the JSON to convert the data to tabular format?</p></div></div><div class="question--answer--2ASXa"><div data-purpose="safely-set-inner-html:submission:user-answer-body"><p>There should be 48 rows.</p></div></div></div>